CC=gcc
CFLAGS= -Wextra -Wall
all: main
main: pointers_1 pointers_2 pointers_3 pointers_array pointers_function
clean:
	rm -f pointers_1 pointers_2 pointers_3 pointers_constant pointers_array pointers_function
